### ISSUE TITLE
requested feature: reverse current order

### ISSUE THREAD

**Issue by edrex** [atom/sort-lines#20]

**Comment by izuzak** [comment]
@edrex There's already a [`reverse-sort` command](https://github.com/atom/sort-lines/blob/3d42613027540d354671eb811677739b83ae1953/lib/sort-lines.coffee#L9) -- is that what you're looking for? If not, could you clarify what the difference would be?

**Comment by xpol** [comment]
I suggest that the `reverse-sort` should be just `reverse`.

So `reverse-sort` = `sort` + `reverse`.

This should be more flexible.

**Comment by alexander-ii** [comment]
I second that.

**Comment by daviscabral** [comment]
Hey guys - I couple of months ago I ended creating a package that does that and it's based in this package. Would be possible to get that merged instead of having it as a different project since it is following the same code conventions and style guide?

Here is the repository: https://github.com/daviscabral/atom-reverse-lines
