### ISSUE TITLE
Disable shortcut F5 when no lines are selected

### ISSUE THREAD

**Issue by Janghou** [atom/sort-lines#28]
Accidently hitting F5 in a any file will sort the file, which is of no use, because it will break most files, e.g. PHP, HTML.

This will confuse users, sure CTRL Z is the rescue.

I think the F5 shortcut should only work on selected lines.
Usecases for sorting a complete file are rare, if any, Command Palette can be used then.

**Comment by eddiemonge** [comment]
This seems like a good idea.

**Comment by adriaanzon** [comment]
:+1:

**Comment by lee-dohm** [comment]
We understand that some people don't like the <kbd>F5</kbd> keybinding. It is also clear that some do. Due to feedback from the community, we added the ability to quickly and easily disable all keybindings in a package:

<img width="875" alt="disable-keybindings" src="https://cloud.githubusercontent.com/assets/1038121/12159204/28418f9e-b495-11e5-8c15-834778fac13d.png">

It is impossible to please everyone with the keybindings, so we have chosen what we feel are sensible defaults guided by the underlying platform and what we feel are standards in other editors.

Due to all of the above, we're going to stick with the keybindings as they are.

If someone wants to submit a PR with a *new* command that only works on selected lines that people could map to <kbd>F5</kbd> or whatever key they wish, we'd be open to accepting that.

**Comment by kankaristo** [comment]
@lee-dohm, would you still consider disabling sorting of all lines when no lines are selected?

No matter what the keybinding is (default or user-selected), it's silly to sort the entire file by default. Selecting all lines (or any that you want to sort) first would be much better.

**Comment by lee-dohm** [comment]
> would you still consider disabling sorting of all lines when no lines are selected?

The problem with changing the defaults of a package is that it impacts many users that aren't involved in this discussion. They aren't involved in this discussion because everything works the way they expect, so they have no reason to come here. At least until we change the defaults.

Since this is:

* Not destructive
* Easily remedied using Undo
* Easily disabled or changed via the standard keybindings support

we're going to preserve the current behavior.

As I said, we would be open to a PR that adds new behavior to the package that works the way you suggest to make it so that the functionality you prefer is more easily available.

Thanks for your passion and interest in Atom!
