### ISSUE TITLE
F5

### ISSUE THREAD

**Issue by claudiojs** [atom/sort-lines#31]
Good plugin, but the shortcut ist the worst that could ever be bound. I don't believe I must explain why. Off course it can be overwritten, but it shouldn't even be set. Could you please remove it?

**Comment by benogle** [comment]
> I don't believe I must explain why

Pleas do, actually, explain why you do not like it.

**Comment by claudiojs** [comment]
A lot of us are webdevelopers and F5 is the stardard key to refresh the browser. I work with two monitors and often Atom and some browser are opened in each one. Sometimes if I switch too fast between these and other programms I really don't known which one has the focus. If I press F5, I expect that the current page in browser is reloaded or nothing happens.

**Comment by JedWatson** [comment]
I am hugely in favour of the `f5` shortcut, because this is what Sublime Text uses. So its very natural for any user migrating to Atom from Sublime Text. (may also be the same in other editors? I'm not sure)

The only complaint I would have in that regard is that Sublime's binding defaults to case-insensitive sort, so I had to go through the source code to figure out how to change that.

**Comment by Xcodo** [comment]
I think that F5 is dangerous too. My default instinct is to hit that to reload things like the diff markings after commiting, it took me a couple of confused files to work out what was going on.

Some of us don't come from Sublime Text!

**Comment by eddiemonge** [comment]
I don't come from Sublime and I still like it.

1) A lot of programs use different keys for different things. To refresh in my browsers (Mac), I use CMD+R so F5 is meaningless for me
2) If you are still manually pressing refresh, its time to update your dev process so it happens automatically for you?

**Comment by kankaristo** [comment]
I find the `F5` shortcut really annoying as well. It probably doesn't affect OS X users, but Windows and Linux users probably find it awkward and annoying. I always have browsers open on my second monitor (documentation, GitHub, Slack, etc.) and often accidentally press `F5` in Atom.

A fix to https://github.com/atom/sort-lines/issues/28 might be a better solution, since some people seem to like it. That way you'd have to press `Ctrl-A` followed by `F5` to sort the entire file, instead of doing it accidentally.

**Comment by jrial** [comment]
The average developer doesn't need to sort lines that often that it warrants a one-key shortcut. They're scarce, so they should be reserved for oft-used functionality. Especially if the shortcut is commonly used in other applications the developer uses, and the action to which you want to bind it is destructive in nature (sorting lines in source code destroys the logic).

Just because Sublime used bad judgement doesn't mean we need to replicate it. Besides, I don't think all versions of Sublime bind it to F5 anyway; my default key bindings in ST2 use F9 and I don't remember having changed it.

**Comment by lee-dohm** [comment]
We understand that some people don't like the <kbd>F5</kbd> keybinding. It is also clear that some do. Due to feedback from the community, we added the ability to quickly and easily disable all keybindings in a package:

<img width="875" alt="disable-keybindings" src="https://cloud.githubusercontent.com/assets/1038121/12159204/28418f9e-b495-11e5-8c15-834778fac13d.png">

It is impossible to please everyone with the keybindings, so we have chosen what we feel are sensible defaults guided by the underlying platform and what we feel are standards in other editors.

Due to all of the above, we're going to stick with the keybindings as they are.
