### ISSUE TITLE
Removing duplicate lines on very large files causes Atom to become unresponsive

### ISSUE THREAD

**Issue by xixixao** [atom/sort-lines#59]
Sublime manages to remove duplicate lines from a file with 52k lines in under a second. Atom crashes.

**Comment by thomasjo** [comment]
For future reference: [“How do I submit a (good) bug report?”](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report).

The fact some other tool does something in less time is irrelevant, but that Atom crashes on your machine performing said task is highly unfortunate. It would be great if you could provide us with more detailed information; perhaps a gist with an example file that reliably reproduces the crash, what version of Atom you're using, and your OS details.

**Comment by xixixao** [comment]
Sorry, I meant to write that it hangs. I'm on OS X, version 1.5.3.

Here's how you can generate yourself a file with 52k lines:
```coffeescript
coffee -e 'console.log Math.floor Math.random() * 100000 for x in [1..52000];"done"' > test.txt
```

> The fact some other tool does something in less time is irrelevant

I think it's not irrelevant, but you might not care. Which is fair. I am only reporting an issue, not demanding you to fix it (which might or might not be easy).

**Comment by thomasjo** [comment]
Thanks for the additional info!

> I think it's not irrelevant, but you might not care. Which is fair. I am only reporting an issue, not demanding you to fix it (which might or might not be easy).

That something is (perceived) slow is something we care about, but comparing it to e.g. Sublime is not relevant; I'm confident I can beat its performance trivially by using e.g. `awk`.

But the fact that this is crashing your Atom instance is, as I said, very unfortunate. If that problem is reproducible, it's definitely something we should strive to fix in some way or another. Are you able to grab a crash dump? That might be able to help track down the problem.

**Comment by xixixao** [comment]
Once I hit sort lines Atom becomes completely unusable and after a while presents the dialog to close it. I guess the way to debug is to reduce the number of lines to a manegable number, then see if something is slowing it down.

**Comment by thomasjo** [comment]
OK, so it doesn't actually crash.

**Comment by thomasjo** [comment]
I have successfully reproduced the reported problem. The problem lies in the very naive implementation of the [`uniqueLines`](https://github.com/atom/sort-lines/blob/e7aec35db0ff5bb421775ab137adbdd9ecd82b09/lib/sort-lines.coffee#L37-L39) function. It does not scale at all for files of this size. We should probably be using a (native) npm package to filter out duplicates instead of using `Array.prototype.filter`.

Operating on files of this size was likely outside the intended scope of this package when this functionality was originally implemented.

**Comment by xixixao** [comment]
For starters, the algorithm could be O(n) instead of O(n^2), before going for native implementation...

**Comment by sanisetti** [comment]
Hi, I am new to the community, is there any way I can help?
