### ISSUE TITLE
Sorting uses whitespace

### ISSUE THREAD

**Issue by njlg** [atom/sort-lines#67]
I find it weird that sorting lines takes into account the whitespace of the line. Can we trim each line before determining the correct order?

Something like this:
```coffee
sortLines = (editor) ->
  sortTextLines editor, (textLines) ->
    textLines.sort (a, b) -> a.trim().localeCompare(b.trim())
```

**Comment by rasenplanscher** [comment]
What's your use-case? Different indentation seems to suggest to me that there's something off with your code or you sort lines from different scopes.

Trimming would add complexity, so there should be a solid use-case for this.

**Comment by njlg** [comment]
Use case: Pasting text into an editor and sorting the lines

**Comment by rasenplanscher** [comment]
If you paste this input:
```
  a
      c
b
```

Do you want to keep working with this:
```
  a
b
      c
```

Or with this:
```
a
b
c
```

In the first case, what use is that?

In the second case, just trim your paste before sorting.

**Comment by njlg** [comment]
Image that all of those letters are visually aligned and you sort it to find the letters out of order, because they had different whitespace. 

Like I said originally I find it awkward that this plugin does not ignore whtiespace. However, if you want to force the user to do a bunch of manual things before the plugin can work like it might in other editors, I suppose it is up to you.

**Comment by rasenplanscher** [comment]
Maybe I should point out two things here:
1. I'm not a core committer and my views do not necessarily represent the atom team
2. I'm not trying to bash you or your request, but rather trying to understand and/or educate

That being said, why don't you just paste a real-world sample of your input and desired output here? Then we can talk about your actual case instead of an abstraction that may very well be too simplified.
